name: sciwms37
channels:
  - conda-forge
  - axiom-data-science
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - c-ares=1.16.1
  - ca-certificates=2020.6.20
  - certifi=2020.6.20
  - cffi=1.14.1
  - cftime=1.2.1
  - cmocean=2.0
  - colorspacious=1.1.2
  - cryptography=3.1
  - curl=7.71.1
  - cycler=0.10.0
  - cython=0.29.21
  - dbus=1.13.6
  - dj-static=0.0.6
  - django=2.2.14
  - django-autoslug=1.9.4
  - django-grappelli=2.14.2
  - django-redis-cache=2.1.1
  - django-typed-models=0.10.0
  - djangorestframework=3.11.1
  - dnspython=1.16.0
  - ecdsa=0.13
  - esmf=8.0.1
  - eventlet=0.26.1
  - expat=2.2.9
  - fontconfig=2.13.1
  - freetype=2.10.2
  - gettext=0.19.8.1
  - glib=2.65.0
  - gmp=6.2.0
  - greenlet=0.4.16
  - gsl=2.6
  - gst-plugins-base=1.14.5
  - gstreamer=1.14.5
  - gunicorn=20.0.4
  - hdf4=4.2.13
  - hdf5=1.10.6
  - hiredis=1.1.0
  - huey=2.1.3
  - icu=64.2
  - idna=2.10
  - isodate=0.6.0
  - jpeg=9d
  - jsonfield=3.1.0
  - kiwisolver=1.2.0
  - krb5=1.17.1
  - ld_impl_linux-64=2.34
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcurl=7.71.1
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.2.1
  - libgcc-ng=9.3.0
  - libgfortran-ng=7.5.0
  - libgomp=9.3.0
  - libiconv=1.16
  - liblapack=3.8.0
  - libnetcdf=4.7.4
  - libnghttp2=1.41.0
  - libopenblas=0.3.10
  - libpng=1.6.37
  - libpq=12.3
  - libspatialindex=1.9.3
  - libssh2=1.9.0
  - libstdcxx-ng=9.3.0
  - libuuid=2.32.1
  - libxcb=1.13
  - libxml2=2.9.10
  - matplotlib=2.2.5
  - matplotlib-base=2.2.5
  - monotonic=1.5
  - nco=4.9.3
  - ncurses=6.2
  - netcdf-fortran=4.5.3
  - netcdf4=1.5.4
  - numpy=1.19.1
  - openssl=1.1.1g
  - pandas=1.1.1
  - pcre=8.44
  - pip=20.2.2
  - proj4=5.2.0
  - psycopg2=2.8.5
  - pthread-stubs=0.4
  - pyaxiom=1.4.6
  - pycparser=2.20
  - pycryptodome=3.9.7
  - pyncml=0.0.9
  - pynco=1.0.0
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyproj=1.9.6
  - pyqt=5.9.2
  - pysgrid=0.3.5
  - pystache=0.5.4
  - python=3.7.8
  - python-dateutil=2.8.1
  - python_abi=3.7
  - pytz=2020.1
  - pyugrid=0.3.1
  - qt=5.9.7
  - readline=8.0
  - redis-py=3.5.3
  - rtree=0.9.4
  - scipy=1.5.2
  - setproctitle=1.1.10
  - setuptools=49.6.0
  - simplejson=3.17.2
  - sip=4.19.8
  - six=1.15.0
  - sqlite=3.33.0
  - sqlparse=0.3.1
  - static=1.1.1
  - tempest-remap=2.0.5
  - tk=8.6.10
  - tornado=6.0.4
  - udunits2=2.2.27.6
  - utide=0.2.5
  - wheel=0.35.1
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.5
  - zlib=1.2.11
